-- ═══════════════════════════════════════════════════════════════
-- HRMS Payroll System - PostgreSQL Database Schema
-- Direct SQL Script (bypasses EF Core migrations)
-- Database: PostgreSQL 18.3
-- ═══════════════════════════════════════════════════════════════

-- Drop existing tables if they exist (in correct order to handle foreign keys)
DROP TABLE IF EXISTS "PayrollAdjustments" CASCADE;
DROP TABLE IF EXISTS "PayrollLeaveRequests" CASCADE;
DROP TABLE IF EXISTS "PayrollAttendancePeriods" CASCADE;
DROP TABLE IF EXISTS "Payrolls" CASCADE;
DROP TABLE IF EXISTS "AttendancePeriodDays" CASCADE;
DROP TABLE IF EXISTS "AttendancePeriods" CASCADE;
DROP TABLE IF EXISTS "Attendances" CASCADE;
DROP TABLE IF EXISTS "Timesheets" CASCADE;
DROP TABLE IF EXISTS "LeaveRequests" CASCADE;
DROP TABLE IF EXISTS "EmployeeLeaveBalances" CASCADE;
DROP TABLE IF EXISTS "Notifications" CASCADE;
DROP TABLE IF EXISTS "Employees" CASCADE;
DROP TABLE IF EXISTS "Users" CASCADE;
DROP TABLE IF EXISTS "LeaveTypes" CASCADE;
DROP TABLE IF EXISTS "PublicHolidays" CASCADE;
DROP TABLE IF EXISTS "Departments" CASCADE;
DROP TABLE IF EXISTS "BankMaster" CASCADE;
DROP TABLE IF EXISTS "__EFMigrationsHistory" CASCADE;

-- ═══════════════════════════════════════════════════════════════
-- Create Tables
-- ═══════════════════════════════════════════════════════════════

-- BankMaster
CREATE TABLE "BankMaster" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text,
    CONSTRAINT "PK_BankMaster" PRIMARY KEY ("Id")
);

-- Departments
CREATE TABLE "Departments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
);

-- LeaveTypes
CREATE TABLE "LeaveTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Code" text NOT NULL,
    "Description" text,
    "DefaultDaysPerYear" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "RequiresApproval" boolean NOT NULL,
    "IsPaid" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LeaveTypes" PRIMARY KEY ("Id")
);

-- PublicHolidays
CREATE TABLE "PublicHolidays" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Year" integer NOT NULL,
    "IsNational" boolean NOT NULL,
    "State" text,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PublicHolidays" PRIMARY KEY ("Id")
);

-- Users
CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Email" character varying(255) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

-- Employees
CREATE TABLE "Employees" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeCode" character varying(20) NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Email" text NOT NULL,
    "PhoneNumber" text,
    "DateOfBirth" timestamp with time zone,
    "Gender" text,
    "Address" text,
    "City" text,
    "State" text,
    "PostalCode" text,
    "Country" text,
    "DepartmentId" integer,
    "Designation" text,
    "JoiningDate" timestamp with time zone NOT NULL,
    "EmploymentType" text,
    "Salary" numeric(18,2) NOT NULL,
    "BankId" integer,
    "BankAccountNumber" text,
    "PanNumber" text,
    "AadharNumber" text,
    "PfNumber" text,
    "EsiNumber" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Employees_BankMaster_BankId" FOREIGN KEY ("BankId") REFERENCES "BankMaster" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Employees_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE SET NULL
);

-- Attendances
CREATE TABLE "Attendances" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "TimeIn" timestamp with time zone,
    "TimeOut" timestamp with time zone,
    "WorkHours" numeric(10,2) NOT NULL,
    "Status" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Attendances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Attendances_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE
);

-- AttendancePeriods
CREATE TABLE "AttendancePeriods" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "TotalDays" integer NOT NULL,
    "WorkingDays" integer NOT NULL,
    "PresentDays" integer NOT NULL,
    "AbsentDays" integer NOT NULL,
    "LeaveDays" integer NOT NULL,
    "HolidayDays" integer NOT NULL,
    "TotalHours" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AttendancePeriods" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AttendancePeriods_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE
);

-- AttendancePeriodDays
CREATE TABLE "AttendancePeriodDays" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AttendancePeriodId" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "DayType" text NOT NULL,
    "Hours" numeric(5,2) NOT NULL,
    "Remarks" text,
    CONSTRAINT "PK_AttendancePeriodDays" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AttendancePeriodDays_AttendancePeriods_AttendancePeriodId" FOREIGN KEY ("AttendancePeriodId") REFERENCES "AttendancePeriods" ("Id") ON DELETE CASCADE
);

-- EmployeeLeaveBalances
CREATE TABLE "EmployeeLeaveBalances" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "LeaveTypeId" integer NOT NULL,
    "Year" integer NOT NULL,
    "TotalDays" numeric(5,2) NOT NULL,
    "UsedDays" numeric(5,2) NOT NULL,
    "BalanceDays" numeric(5,2) NOT NULL,
    "CarryForwardDays" numeric(5,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_EmployeeLeaveBalances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmployeeLeaveBalances_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EmployeeLeaveBalances_LeaveTypes_LeaveTypeId" FOREIGN KEY ("LeaveTypeId") REFERENCES "LeaveTypes" ("Id") ON DELETE CASCADE
);

-- LeaveRequests
CREATE TABLE "LeaveRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "LeaveTypeId" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "TotalDays" numeric(5,2) NOT NULL,
    "Reason" text NOT NULL,
    "Status" text NOT NULL,
    "ApprovedBy" integer,
    "ApprovedDate" timestamp with time zone,
    "ApproverRemarks" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LeaveRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LeaveRequests_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LeaveRequests_LeaveTypes_LeaveTypeId" FOREIGN KEY ("LeaveTypeId") REFERENCES "LeaveTypes" ("Id") ON DELETE RESTRICT
);

-- Notifications
CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "Type" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReadAt" timestamp with time zone,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

-- Payrolls
CREATE TABLE "Payrolls" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "Month" integer NOT NULL,
    "Year" integer NOT NULL,
    "BasicSalary" numeric(18,2) NOT NULL,
    "Allowances" numeric(18,2) NOT NULL,
    "Deductions" numeric(18,2) NOT NULL,
    "EpfAmount" numeric(18,2) NOT NULL,
    "SocsoAmount" numeric(18,2) NOT NULL,
    "TaxAmount" numeric(18,2) NOT NULL,
    "GrossIncome" numeric(18,2) NOT NULL,
    "NetSalary" numeric(18,2) NOT NULL,
    "Status" text NOT NULL,
    "ProcessedDate" timestamp with time zone,
    "ProcessedBy" integer,
    "ApprovedDate" timestamp with time zone,
    "ApprovedBy" integer,
    "PaidDate" timestamp with time zone,
    "PaymentMethod" text,
    "TransactionId" text,
    "Remarks" text,
    "AttendanceHours" numeric(10,2) NOT NULL,
    "ExpectedHours" numeric(10,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Payrolls" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payrolls_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Payrolls_Users_ApprovedBy" FOREIGN KEY ("ApprovedBy") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Payrolls_Users_ProcessedBy" FOREIGN KEY ("ProcessedBy") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

-- PayrollAdjustments
CREATE TABLE "PayrollAdjustments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PayrollId" integer NOT NULL,
    "Type" text NOT NULL,
    "Description" text NOT NULL,
    "Amount" numeric(10,2) NOT NULL,
    "CreatedBy" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PayrollAdjustments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PayrollAdjustments_Payrolls_PayrollId" FOREIGN KEY ("PayrollId") REFERENCES "Payrolls" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PayrollAdjustments_Users_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

-- PayrollAttendancePeriods
CREATE TABLE "PayrollAttendancePeriods" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PayrollId" integer NOT NULL,
    "AttendancePeriodId" integer NOT NULL,
    "HoursWorked" numeric(10,2) NOT NULL,
    CONSTRAINT "PK_PayrollAttendancePeriods" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PayrollAttendancePeriods_AttendancePeriods_AttendanceP~" FOREIGN KEY ("AttendancePeriodId") REFERENCES "AttendancePeriods" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PayrollAttendancePeriods_Payrolls_PayrollId" FOREIGN KEY ("PayrollId") REFERENCES "Payrolls" ("Id") ON DELETE CASCADE
);

-- PayrollLeaveRequests
CREATE TABLE "PayrollLeaveRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PayrollId" integer NOT NULL,
    "LeaveRequestId" integer NOT NULL,
    "LeaveDays" numeric(5,2) NOT NULL,
    "DeductionAmount" numeric(10,2) NOT NULL,
    CONSTRAINT "PK_PayrollLeaveRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PayrollLeaveRequests_LeaveRequests_LeaveRequestId" FOREIGN KEY ("LeaveRequestId") REFERENCES "LeaveRequests" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PayrollLeaveRequests_Payrolls_PayrollId" FOREIGN KEY ("PayrollId") REFERENCES "Payrolls" ("Id") ON DELETE CASCADE
);

-- Timesheets
CREATE TABLE "Timesheets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "Year" integer NOT NULL,
    "Month" integer NOT NULL,
    "TotalWorkHours" numeric(10,2) NOT NULL,
    "Status" text NOT NULL,
    "SubmittedDate" timestamp with time zone,
    "ApprovedDate" timestamp with time zone,
    "ApprovedBy" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Timesheets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Timesheets_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE
);

-- ═══════════════════════════════════════════════════════════════
-- Create Indexes
-- ═══════════════════════════════════════════════════════════════

CREATE UNIQUE INDEX "IX_AttendancePeriodDays_AttendancePeriodId_Date" ON "AttendancePeriodDays" ("AttendancePeriodId", "Date");

CREATE UNIQUE INDEX "IX_AttendancePeriods_EmployeeId_StartDate_EndDate" ON "AttendancePeriods" ("EmployeeId", "StartDate", "EndDate");

CREATE UNIQUE INDEX "IX_Attendances_EmployeeId_Date" ON "Attendances" ("EmployeeId", "Date");

CREATE UNIQUE INDEX "IX_EmployeeLeaveBalances_EmployeeId_LeaveTypeId_Year" ON "EmployeeLeaveBalances" ("EmployeeId", "LeaveTypeId", "Year");

CREATE INDEX "IX_EmployeeLeaveBalances_LeaveTypeId" ON "EmployeeLeaveBalances" ("LeaveTypeId");

CREATE INDEX "IX_Employees_BankId" ON "Employees" ("BankId");

CREATE INDEX "IX_Employees_DepartmentId" ON "Employees" ("DepartmentId");

CREATE UNIQUE INDEX "IX_Employees_EmployeeCode" ON "Employees" ("EmployeeCode");

CREATE INDEX "IX_LeaveRequests_EmployeeId" ON "LeaveRequests" ("EmployeeId");

CREATE INDEX "IX_LeaveRequests_LeaveTypeId" ON "LeaveRequests" ("LeaveTypeId");

CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

CREATE INDEX "IX_PayrollAdjustments_CreatedBy" ON "PayrollAdjustments" ("CreatedBy");

CREATE INDEX "IX_PayrollAdjustments_PayrollId" ON "PayrollAdjustments" ("PayrollId");

CREATE INDEX "IX_PayrollAttendancePeriods_AttendancePeriodId" ON "PayrollAttendancePeriods" ("AttendancePeriodId");

CREATE UNIQUE INDEX "IX_PayrollAttendancePeriods_PayrollId_AttendancePeriodId" ON "PayrollAttendancePeriods" ("PayrollId", "AttendancePeriodId");

CREATE INDEX "IX_PayrollLeaveRequests_LeaveRequestId" ON "PayrollLeaveRequests" ("LeaveRequestId");

CREATE UNIQUE INDEX "IX_PayrollLeaveRequests_PayrollId_LeaveRequestId" ON "PayrollLeaveRequests" ("PayrollId", "LeaveRequestId");

CREATE INDEX "IX_Payrolls_ApprovedBy" ON "Payrolls" ("ApprovedBy");

CREATE UNIQUE INDEX "IX_Payrolls_EmployeeId_Month_Year" ON "Payrolls" ("EmployeeId", "Month", "Year");

CREATE INDEX "IX_Payrolls_ProcessedBy" ON "Payrolls" ("ProcessedBy");

CREATE UNIQUE INDEX "IX_Timesheets_EmployeeId_Year_Month" ON "Timesheets" ("EmployeeId", "Year", "Month");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email") WHERE "Email" IS NOT NULL AND "Email" <> '';

-- ═══════════════════════════════════════════════════════════════
-- Create EF Migrations History Table
-- ═══════════════════════════════════════════════════════════════

CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- Insert migration record
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260516075928_InitialCreate', '8.0.0');

-- ═══════════════════════════════════════════════════════════════
-- Seed Data - Leave Types
-- ═══════════════════════════════════════════════════════════════

INSERT INTO "LeaveTypes" ("Name", "Code", "Description", "DefaultDaysPerYear", "IsActive", "RequiresApproval", "IsPaid", "CreatedAt")
VALUES 
    ('Annual Leave', 'AL', 'Annual paid leave', 14, true, true, true, NOW()),
    ('Medical Leave', 'ML', 'Medical/Sick leave', 14, true, true, true, NOW()),
    ('Emergency Leave', 'EL', 'Emergency leave', 5, true, true, true, NOW()),
    ('Unpaid Leave', 'UL', 'Unpaid leave', 0, true, true, false, NOW()),
    ('Maternity Leave', 'MAT', 'Maternity leave for female employees', 60, true, true, true, NOW()),
    ('Paternity Leave', 'PAT', 'Paternity leave for male employees', 7, true, true, true, NOW());

-- ═══════════════════════════════════════════════════════════════
-- Seed Data - Default Admin User
-- ═══════════════════════════════════════════════════════════════
-- Username: admin
-- Password: Admin@123
-- Email: admin@hrms.local

INSERT INTO "Users" ("Username", "Email", "PasswordHash", "Role", "IsActive", "CreatedAt")
VALUES ('admin', 'admin@hrms.local', '$2a$11$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Admin', true, NOW());

-- ═══════════════════════════════════════════════════════════════
-- Script Complete
-- ═══════════════════════════════════════════════════════════════

-- Verify table creation
SELECT 
    table_name,
    (SELECT COUNT(*) FROM information_schema.columns WHERE table_name = t.table_name) as column_count
FROM information_schema.tables t
WHERE table_schema = 'public' 
  AND table_type = 'BASE TABLE'
ORDER BY table_name;
