-- ═══════════════════════════════════════════════════════════════
-- Part 3: Payroll tables, indexes, and seed data
-- ═══════════════════════════════════════════════════════════════

-- Payrolls
CREATE TABLE "Payrolls" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "Month" integer NOT NULL,
    "Year" integer NOT NULL,
    "BasicSalary" numeric(18,2) NOT NULL,
    "Allowances" numeric(18,2) NOT NULL,
    "Deductions" numeric(18,2) NOT NULL,
    "EpfAmount" numeric(18,2) NOT NULL,
    "SocsoAmount" numeric(18,2) NOT NULL,
    "TaxAmount" numeric(18,2) NOT NULL,
    "GrossIncome" numeric(18,2) NOT NULL,
    "NetSalary" numeric(18,2) NOT NULL,
    "Status" text NOT NULL,
    "ProcessedDate" timestamp with time zone,
    "ProcessedBy" integer,
    "ApprovedDate" timestamp with time zone,
    "ApprovedBy" integer,
    "PaidDate" timestamp with time zone,
    "PaymentMethod" text,
    "TransactionId" text,
    "Remarks" text,
    "AttendanceHours" numeric(10,2) NOT NULL,
    "ExpectedHours" numeric(10,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Payrolls" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payrolls_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Payrolls_Users_ApprovedBy" FOREIGN KEY ("ApprovedBy") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Payrolls_Users_ProcessedBy" FOREIGN KEY ("ProcessedBy") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

-- PayrollAdjustments
CREATE TABLE "PayrollAdjustments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PayrollId" integer NOT NULL,
    "Type" text NOT NULL,
    "Description" text NOT NULL,
    "Amount" numeric(10,2) NOT NULL,
    "CreatedBy" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PayrollAdjustments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PayrollAdjustments_Payrolls_PayrollId" FOREIGN KEY ("PayrollId") REFERENCES "Payrolls" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PayrollAdjustments_Users_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

-- PayrollAttendancePeriods
CREATE TABLE "PayrollAttendancePeriods" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PayrollId" integer NOT NULL,
    "AttendancePeriodId" integer NOT NULL,
    "HoursWorked" numeric(10,2) NOT NULL,
    CONSTRAINT "PK_PayrollAttendancePeriods" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PayrollAttendancePeriods_AttendancePeriods_AttendanceP~" FOREIGN KEY ("AttendancePeriodId") REFERENCES "AttendancePeriods" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PayrollAttendancePeriods_Payrolls_PayrollId" FOREIGN KEY ("PayrollId") REFERENCES "Payrolls" ("Id") ON DELETE CASCADE
);

-- PayrollLeaveRequests
CREATE TABLE "PayrollLeaveRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PayrollId" integer NOT NULL,
    "LeaveRequestId" integer NOT NULL,
    "LeaveDays" numeric(5,2) NOT NULL,
    "DeductionAmount" numeric(10,2) NOT NULL,
    CONSTRAINT "PK_PayrollLeaveRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PayrollLeaveRequests_LeaveRequests_LeaveRequestId" FOREIGN KEY ("LeaveRequestId") REFERENCES "LeaveRequests" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PayrollLeaveRequests_Payrolls_PayrollId" FOREIGN KEY ("PayrollId") REFERENCES "Payrolls" ("Id") ON DELETE CASCADE
);

-- Create Indexes
CREATE UNIQUE INDEX "IX_AttendancePeriodDays_AttendancePeriodId_Date" ON "AttendancePeriodDays" ("AttendancePeriodId", "Date");
CREATE UNIQUE INDEX "IX_AttendancePeriods_EmployeeId_StartDate_EndDate" ON "AttendancePeriods" ("EmployeeId", "StartDate", "EndDate");
CREATE UNIQUE INDEX "IX_Attendances_EmployeeId_Date" ON "Attendances" ("EmployeeId", "Date");
CREATE UNIQUE INDEX "IX_EmployeeLeaveBalances_EmployeeId_LeaveTypeId_Year" ON "EmployeeLeaveBalances" ("EmployeeId", "LeaveTypeId", "Year");
CREATE INDEX "IX_EmployeeLeaveBalances_LeaveTypeId" ON "EmployeeLeaveBalances" ("LeaveTypeId");
CREATE INDEX "IX_Employees_BankId" ON "Employees" ("BankId");
CREATE INDEX "IX_Employees_DepartmentId" ON "Employees" ("DepartmentId");
CREATE UNIQUE INDEX "IX_Employees_EmployeeCode" ON "Employees" ("EmployeeCode");
CREATE INDEX "IX_LeaveRequests_EmployeeId" ON "LeaveRequests" ("EmployeeId");
CREATE INDEX "IX_LeaveRequests_LeaveTypeId" ON "LeaveRequests" ("LeaveTypeId");
CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");
CREATE INDEX "IX_PayrollAdjustments_CreatedBy" ON "PayrollAdjustments" ("CreatedBy");
CREATE INDEX "IX_PayrollAdjustments_PayrollId" ON "PayrollAdjustments" ("PayrollId");
CREATE INDEX "IX_PayrollAttendancePeriods_AttendancePeriodId" ON "PayrollAttendancePeriods" ("AttendancePeriodId");
CREATE UNIQUE INDEX "IX_PayrollAttendancePeriods_PayrollId_AttendancePeriodId" ON "PayrollAttendancePeriods" ("PayrollId", "AttendancePeriodId");
CREATE INDEX "IX_PayrollLeaveRequests_LeaveRequestId" ON "PayrollLeaveRequests" ("LeaveRequestId");
CREATE UNIQUE INDEX "IX_PayrollLeaveRequests_PayrollId_LeaveRequestId" ON "PayrollLeaveRequests" ("PayrollId", "LeaveRequestId");
CREATE INDEX "IX_Payrolls_ApprovedBy" ON "Payrolls" ("ApprovedBy");
CREATE UNIQUE INDEX "IX_Payrolls_EmployeeId_Month_Year" ON "Payrolls" ("EmployeeId", "Month", "Year");
CREATE INDEX "IX_Payrolls_ProcessedBy" ON "Payrolls" ("ProcessedBy");
CREATE UNIQUE INDEX "IX_Timesheets_EmployeeId_Year_Month" ON "Timesheets" ("EmployeeId", "Year", "Month");
CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email") WHERE "Email" IS NOT NULL AND "Email" <> '';

-- Create EF Migrations History
CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260516075928_InitialCreate', '8.0.0');

-- Seed Leave Types
INSERT INTO "LeaveTypes" ("Name", "Code", "Description", "DefaultDaysPerYear", "IsActive", "RequiresApproval", "IsPaid", "CreatedAt")
VALUES 
    ('Annual Leave', 'AL', 'Annual paid leave', 14, true, true, true, NOW()),
    ('Medical Leave', 'ML', 'Medical/Sick leave', 14, true, true, true, NOW()),
    ('Emergency Leave', 'EL', 'Emergency leave', 5, true, true, true, NOW()),
    ('Unpaid Leave', 'UL', 'Unpaid leave', 0, true, true, false, NOW()),
    ('Maternity Leave', 'MAT', 'Maternity leave for female employees', 60, true, true, true, NOW()),
    ('Paternity Leave', 'PAT', 'Paternity leave for male employees', 7, true, true, true, NOW());

-- Seed Admin User (Username: admin, Password: Admin@123)
INSERT INTO "Users" ("Username", "Email", "PasswordHash", "Role", "IsActive", "CreatedAt")
VALUES ('admin', 'admin@hrms.local', '$2a$11$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Admin', true, NOW());

-- Final Verification
SELECT 'Part 3 Complete - ALL DONE!' as status;
SELECT table_name, 
       (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = 'public' AND table_name = t.table_name) as columns
FROM information_schema.tables t
WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
ORDER BY table_name;
