-- ═══════════════════════════════════════════════════════════════
-- Part 2: Create related tables (attendance, leave, payroll, notifications)
-- ═══════════════════════════════════════════════════════════════

-- Attendances
CREATE TABLE "Attendances" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "TimeIn" timestamp with time zone,
    "TimeOut" timestamp with time zone,
    "WorkHours" numeric(10,2) NOT NULL,
    "Status" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Attendances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Attendances_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE
);

-- AttendancePeriods
CREATE TABLE "AttendancePeriods" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "TotalDays" integer NOT NULL,
    "WorkingDays" integer NOT NULL,
    "PresentDays" integer NOT NULL,
    "AbsentDays" integer NOT NULL,
    "LeaveDays" integer NOT NULL,
    "HolidayDays" integer NOT NULL,
    "TotalHours" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AttendancePeriods" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AttendancePeriods_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE
);

-- AttendancePeriodDays
CREATE TABLE "AttendancePeriodDays" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AttendancePeriodId" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "DayType" text NOT NULL,
    "Hours" numeric(5,2) NOT NULL,
    "Remarks" text,
    CONSTRAINT "PK_AttendancePeriodDays" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AttendancePeriodDays_AttendancePeriods_AttendancePeriodId" FOREIGN KEY ("AttendancePeriodId") REFERENCES "AttendancePeriods" ("Id") ON DELETE CASCADE
);

-- EmployeeLeaveBalances
CREATE TABLE "EmployeeLeaveBalances" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "LeaveTypeId" integer NOT NULL,
    "Year" integer NOT NULL,
    "TotalDays" numeric(5,2) NOT NULL,
    "UsedDays" numeric(5,2) NOT NULL,
    "BalanceDays" numeric(5,2) NOT NULL,
    "CarryForwardDays" numeric(5,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_EmployeeLeaveBalances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmployeeLeaveBalances_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EmployeeLeaveBalances_LeaveTypes_LeaveTypeId" FOREIGN KEY ("LeaveTypeId") REFERENCES "LeaveTypes" ("Id") ON DELETE CASCADE
);

-- LeaveRequests
CREATE TABLE "LeaveRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "LeaveTypeId" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "TotalDays" numeric(5,2) NOT NULL,
    "Reason" text NOT NULL,
    "Status" text NOT NULL,
    "ApprovedBy" integer,
    "ApprovedDate" timestamp with time zone,
    "ApproverRemarks" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LeaveRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LeaveRequests_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LeaveRequests_LeaveTypes_LeaveTypeId" FOREIGN KEY ("LeaveTypeId") REFERENCES "LeaveTypes" ("Id") ON DELETE RESTRICT
);

-- Notifications
CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "Type" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReadAt" timestamp with time zone,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

-- Timesheets
CREATE TABLE "Timesheets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "Year" integer NOT NULL,
    "Month" integer NOT NULL,
    "TotalWorkHours" numeric(10,2) NOT NULL,
    "Status" text NOT NULL,
    "SubmittedDate" timestamp with time zone,
    "ApprovedDate" timestamp with time zone,
    "ApprovedBy" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Timesheets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Timesheets_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE
);

-- Verify Part 2
SELECT 'Part 2 Complete - Related tables created' as status;
SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name;
