-- ═══════════════════════════════════════════════════════════════
-- Part 1: Drop existing tables and create core tables
-- ═══════════════════════════════════════════════════════════════

-- Drop all tables
DROP TABLE IF EXISTS "PayrollAdjustments" CASCADE;
DROP TABLE IF EXISTS "PayrollLeaveRequests" CASCADE;
DROP TABLE IF EXISTS "PayrollAttendancePeriods" CASCADE;
DROP TABLE IF EXISTS "Payrolls" CASCADE;
DROP TABLE IF EXISTS "AttendancePeriodDays" CASCADE;
DROP TABLE IF EXISTS "AttendancePeriods" CASCADE;
DROP TABLE IF EXISTS "Attendances" CASCADE;
DROP TABLE IF EXISTS "Timesheets" CASCADE;
DROP TABLE IF EXISTS "LeaveRequests" CASCADE;
DROP TABLE IF EXISTS "EmployeeLeaveBalances" CASCADE;
DROP TABLE IF EXISTS "Notifications" CASCADE;
DROP TABLE IF EXISTS "Employees" CASCADE;
DROP TABLE IF EXISTS "Users" CASCADE;
DROP TABLE IF EXISTS "LeaveTypes" CASCADE;
DROP TABLE IF EXISTS "PublicHolidays" CASCADE;
DROP TABLE IF EXISTS "Departments" CASCADE;
DROP TABLE IF EXISTS "BankMaster" CASCADE;
DROP TABLE IF EXISTS "__EFMigrationsHistory" CASCADE;

-- BankMaster
CREATE TABLE "BankMaster" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text,
    CONSTRAINT "PK_BankMaster" PRIMARY KEY ("Id")
);

-- Departments
CREATE TABLE "Departments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
);

-- LeaveTypes
CREATE TABLE "LeaveTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Code" text NOT NULL,
    "Description" text,
    "DefaultDaysPerYear" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "RequiresApproval" boolean NOT NULL,
    "IsPaid" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LeaveTypes" PRIMARY KEY ("Id")
);

-- PublicHolidays
CREATE TABLE "PublicHolidays" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Year" integer NOT NULL,
    "IsNational" boolean NOT NULL,
    "State" text,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PublicHolidays" PRIMARY KEY ("Id")
);

-- Users
CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Email" character varying(255) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

-- Employees
CREATE TABLE "Employees" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeCode" character varying(20) NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Email" text NOT NULL,
    "PhoneNumber" text,
    "DateOfBirth" timestamp with time zone,
    "Gender" text,
    "Address" text,
    "City" text,
    "State" text,
    "PostalCode" text,
    "Country" text,
    "DepartmentId" integer,
    "Designation" text,
    "JoiningDate" timestamp with time zone NOT NULL,
    "EmploymentType" text,
    "Salary" numeric(18,2) NOT NULL,
    "BankId" integer,
    "BankAccountNumber" text,
    "PanNumber" text,
    "AadharNumber" text,
    "PfNumber" text,
    "EsiNumber" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Employees_BankMaster_BankId" FOREIGN KEY ("BankId") REFERENCES "BankMaster" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Employees_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE SET NULL
);

-- Verify Part 1
SELECT 'Part 1 Complete - Core tables created' as status;
SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name;
