[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
  "cd HrmsApi",
  "dotnet restore",
  "dotnet build -c Release -o /app/build"
]

[phases.install]
cmds = ["dotnet publish HrmsApi/HrmsApi.csproj -c Release -o /app/publish"]

[start]
cmd = "cd /app/publish && dotnet HrmsApi.dll --urls=http://0.0.0.0:$PORT"
