[phases.setup]
nixPkgs = ["nodejs", "dotnet-sdk_8"]

[phases.build]
cmds = [
  "cd HrmsApi && dotnet restore",
  "cd HrmsApi && dotnet build -c Release",
  "cd hrms-ui && npm install",
  "cd hrms-ui && npm run build"
]

[phases.deploy]
cmds = ["cd HrmsApi && dotnet HrmsApi.dll"]

[start]
cmd = "cd HrmsApi && dotnet run --urls=http://0.0.0.0:$PORT"
