-- ═══════════════════════════════════════════════════════════════
-- Railway Database Setup - Run each section ONE AT A TIME
-- Copy and run each section between the === markers
-- ═══════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════
-- STEP 1: Clean up test table and drop existing tables
-- ═══════════════════════════════════════════════════════════════
DROP TABLE IF EXISTS test_simple;
DROP TABLE IF EXISTS "PayrollAdjustments" CASCADE;
DROP TABLE IF EXISTS "PayrollLeaveRequests" CASCADE;
DROP TABLE IF EXISTS "PayrollAttendancePeriods" CASCADE;
DROP TABLE IF EXISTS "Payrolls" CASCADE;
DROP TABLE IF EXISTS "AttendancePeriodDays" CASCADE;
DROP TABLE IF EXISTS "AttendancePeriods" CASCADE;
DROP TABLE IF EXISTS "Attendances" CASCADE;
DROP TABLE IF EXISTS "Timesheets" CASCADE;
DROP TABLE IF EXISTS "LeaveRequests" CASCADE;
DROP TABLE IF EXISTS "EmployeeLeaveBalances" CASCADE;
DROP TABLE IF EXISTS "Notifications" CASCADE;
DROP TABLE IF EXISTS "Employees" CASCADE;
DROP TABLE IF EXISTS "Users" CASCADE;
DROP TABLE IF EXISTS "LeaveTypes" CASCADE;
DROP TABLE IF EXISTS "PublicHolidays" CASCADE;
DROP TABLE IF EXISTS "Departments" CASCADE;
DROP TABLE IF EXISTS "BankMaster" CASCADE;
-- Keep __EFMigrationsHistory for now

-- ═══════════════════════════════════════════════════════════════
-- STEP 2: Create BankMaster
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE "BankMaster" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text,
    CONSTRAINT "PK_BankMaster" PRIMARY KEY ("Id")
);

-- ═══════════════════════════════════════════════════════════════
-- STEP 3: Create Departments
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE "Departments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
);

-- ═══════════════════════════════════════════════════════════════
-- STEP 4: Create LeaveTypes
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE "LeaveTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Code" text NOT NULL,
    "Description" text,
    "DefaultDaysPerYear" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "RequiresApproval" boolean NOT NULL,
    "IsPaid" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LeaveTypes" PRIMARY KEY ("Id")
);

-- ═══════════════════════════════════════════════════════════════
-- STEP 5: Create PublicHolidays
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE "PublicHolidays" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Year" integer NOT NULL,
    "IsNational" boolean NOT NULL,
    "State" text,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PublicHolidays" PRIMARY KEY ("Id")
);

-- ═══════════════════════════════════════════════════════════════
-- STEP 6: Create Users
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Email" character varying(255) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

-- ═══════════════════════════════════════════════════════════════
-- STEP 7: Create Employees
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE "Employees" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeCode" character varying(20) NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Email" text NOT NULL,
    "PhoneNumber" text,
    "DateOfBirth" timestamp with time zone,
    "Gender" text,
    "Address" text,
    "City" text,
    "State" text,
    "PostalCode" text,
    "Country" text,
    "DepartmentId" integer,
    "Designation" text,
    "JoiningDate" timestamp with time zone NOT NULL,
    "EmploymentType" text,
    "Salary" numeric(18,2) NOT NULL,
    "BankId" integer,
    "BankAccountNumber" text,
    "PanNumber" text,
    "AadharNumber" text,
    "PfNumber" text,
    "EsiNumber" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Employees_BankMaster_BankId" FOREIGN KEY ("BankId") REFERENCES "BankMaster" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Employees_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id") ON DELETE SET NULL
);

-- ═══════════════════════════════════════════════════════════════
-- STEP 8: Create Attendances
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE "Attendances" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "TimeIn" timestamp with time zone,
    "TimeOut" timestamp with time zone,
    "WorkHours" numeric(10,2) NOT NULL,
    "Status" text NOT NULL,
    "Remarks" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Attendances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Attendances_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE
);

-- ═══════════════════════════════════════════════════════════════
-- STEP 9: Create AttendancePeriods
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE "AttendancePeriods" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "TotalDays" integer NOT NULL,
    "WorkingDays" integer NOT NULL,
    "PresentDays" integer NOT NULL,
    "AbsentDays" integer NOT NULL,
    "LeaveDays" integer NOT NULL,
    "HolidayDays" integer NOT NULL,
    "TotalHours" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AttendancePeriods" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AttendancePeriods_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE
);

-- ═══════════════════════════════════════════════════════════════
-- STEP 10: Create AttendancePeriodDays
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE "AttendancePeriodDays" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AttendancePeriodId" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "DayType" text NOT NULL,
    "Hours" numeric(5,2) NOT NULL,
    "Remarks" text,
    CONSTRAINT "PK_AttendancePeriodDays" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AttendancePeriodDays_AttendancePeriods_AttendancePeriodId" FOREIGN KEY ("AttendancePeriodId") REFERENCES "AttendancePeriods" ("Id") ON DELETE CASCADE
);

-- ═══════════════════════════════════════════════════════════════
-- STEP 11: Create EmployeeLeaveBalances
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE "EmployeeLeaveBalances" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "LeaveTypeId" integer NOT NULL,
    "Year" integer NOT NULL,
    "TotalDays" numeric(5,2) NOT NULL,
    "UsedDays" numeric(5,2) NOT NULL,
    "BalanceDays" numeric(5,2) NOT NULL,
    "CarryForwardDays" numeric(5,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_EmployeeLeaveBalances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmployeeLeaveBalances_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EmployeeLeaveBalances_LeaveTypes_LeaveTypeId" FOREIGN KEY ("LeaveTypeId") REFERENCES "LeaveTypes" ("Id") ON DELETE CASCADE
);

-- ═══════════════════════════════════════════════════════════════
-- STEP 12: Create LeaveRequests
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE "LeaveRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "LeaveTypeId" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "TotalDays" numeric(5,2) NOT NULL,
    "Reason" text NOT NULL,
    "Status" text NOT NULL,
    "ApprovedBy" integer,
    "ApprovedDate" timestamp with time zone,
    "ApproverRemarks" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LeaveRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LeaveRequests_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LeaveRequests_LeaveTypes_LeaveTypeId" FOREIGN KEY ("LeaveTypeId") REFERENCES "LeaveTypes" ("Id") ON DELETE RESTRICT
);

-- ═══════════════════════════════════════════════════════════════
-- STEP 13: Create Notifications
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "Type" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReadAt" timestamp with time zone,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

-- ═══════════════════════════════════════════════════════════════
-- STEP 14: Create Timesheets
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE "Timesheets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "Year" integer NOT NULL,
    "Month" integer NOT NULL,
    "TotalWorkHours" numeric(10,2) NOT NULL,
    "Status" text NOT NULL,
    "SubmittedDate" timestamp with time zone,
    "ApprovedDate" timestamp with time zone,
    "ApprovedBy" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Timesheets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Timesheets_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE
);

-- ═══════════════════════════════════════════════════════════════
-- STEP 15: Create Payrolls
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE "Payrolls" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "Month" integer NOT NULL,
    "Year" integer NOT NULL,
    "BasicSalary" numeric(18,2) NOT NULL,
    "Allowances" numeric(18,2) NOT NULL,
    "Deductions" numeric(18,2) NOT NULL,
    "EpfAmount" numeric(18,2) NOT NULL,
    "SocsoAmount" numeric(18,2) NOT NULL,
    "TaxAmount" numeric(18,2) NOT NULL,
    "GrossIncome" numeric(18,2) NOT NULL,
    "NetSalary" numeric(18,2) NOT NULL,
    "Status" text NOT NULL,
    "ProcessedDate" timestamp with time zone,
    "ProcessedBy" integer,
    "ApprovedDate" timestamp with time zone,
    "ApprovedBy" integer,
    "PaidDate" timestamp with time zone,
    "PaymentMethod" text,
    "TransactionId" text,
    "Remarks" text,
    "AttendanceHours" numeric(10,2) NOT NULL,
    "ExpectedHours" numeric(10,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Payrolls" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payrolls_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Payrolls_Users_ApprovedBy" FOREIGN KEY ("ApprovedBy") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Payrolls_Users_ProcessedBy" FOREIGN KEY ("ProcessedBy") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

-- ═══════════════════════════════════════════════════════════════
-- STEP 16: Create PayrollAdjustments
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE "PayrollAdjustments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PayrollId" integer NOT NULL,
    "Type" text NOT NULL,
    "Description" text NOT NULL,
    "Amount" numeric(10,2) NOT NULL,
    "CreatedBy" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PayrollAdjustments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PayrollAdjustments_Payrolls_PayrollId" FOREIGN KEY ("PayrollId") REFERENCES "Payrolls" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PayrollAdjustments_Users_CreatedBy" FOREIGN KEY ("CreatedBy") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

-- ═══════════════════════════════════════════════════════════════
-- STEP 17: Create PayrollAttendancePeriods
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE "PayrollAttendancePeriods" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PayrollId" integer NOT NULL,
    "AttendancePeriodId" integer NOT NULL,
    "HoursWorked" numeric(10,2) NOT NULL,
    CONSTRAINT "PK_PayrollAttendancePeriods" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PayrollAttendancePeriods_AttendancePeriods_AttendanceP~" FOREIGN KEY ("AttendancePeriodId") REFERENCES "AttendancePeriods" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PayrollAttendancePeriods_Payrolls_PayrollId" FOREIGN KEY ("PayrollId") REFERENCES "Payrolls" ("Id") ON DELETE CASCADE
);

-- ═══════════════════════════════════════════════════════════════
-- STEP 18: Create PayrollLeaveRequests
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE "PayrollLeaveRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PayrollId" integer NOT NULL,
    "LeaveRequestId" integer NOT NULL,
    "LeaveDays" numeric(5,2) NOT NULL,
    "DeductionAmount" numeric(10,2) NOT NULL,
    CONSTRAINT "PK_PayrollLeaveRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PayrollLeaveRequests_LeaveRequests_LeaveRequestId" FOREIGN KEY ("LeaveRequestId") REFERENCES "LeaveRequests" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PayrollLeaveRequests_Payrolls_PayrollId" FOREIGN KEY ("PayrollId") REFERENCES "Payrolls" ("Id") ON DELETE CASCADE
);

-- ═══════════════════════════════════════════════════════════════
-- Verify All Tables Created
-- ═══════════════════════════════════════════════════════════════
SELECT table_name FROM information_schema.tables 
WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
ORDER BY table_name;
